-- ===========================================
-- Customer Schema
-- Version 1.0.0 (Beta)
-- ===========================================

-- ===========================================
-- Extensions
-- ===========================================
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===========================================
-- Custom Types
-- ===========================================
DROP TYPE IF EXISTS account_status CASCADE;
DROP TYPE IF EXISTS token_status CASCADE;

CREATE TYPE account_status AS ENUM ('ACTIVE', 'DEACTIVATED', 'DELETED', 'CREATED');
CREATE TYPE token_status   AS ENUM ('PENDING', 'ACTIVE', 'PROCESSING', 'FAILED');

-- ===========================================
-- Clear tables
-- ===========================================
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS customer_addresses CASCADE;
DROP TABLE IF EXISTS customer_payment_methods CASCADE;

-- ===========================================
-- Customers
-- ===========================================
CREATE TABLE customers (
    customer_id                UUID PRIMARY KEY,
    username                   VARCHAR(100) NOT NULL UNIQUE,
    password_hash              VARCHAR(255) NOT NULL,
    phone_number               VARCHAR(25)  NOT NULL UNIQUE,
    email                      VARCHAR(255) NOT NULL UNIQUE,
    customer_name              VARCHAR(255),
    customer_surname           VARCHAR(255),
    subscribed_at              TIMESTAMPTZ,
    subscribed_valid_until_at  TIMESTAMPTZ,
    version                    INT NOT NULL DEFAULT 0,
    status                     account_status NOT NULL DEFAULT 'ACTIVE',
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    password_changed_at        TIMESTAMPTZ,
    deleted_at                 TIMESTAMPTZ
);

-- ===========================================
-- Customer Addresses
-- ===========================================
CREATE TABLE customer_addresses (
    address_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    country        VARCHAR(150) NOT NULL,
    city           VARCHAR(150) NOT NULL,
    street         VARCHAR(150) NOT NULL,
    postal_code    VARCHAR(50)  NOT NULL,
    is_default     BOOLEAN NOT NULL DEFAULT FALSE,
    version        INT NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================
-- Customer Payment Methods
-- ===========================================
CREATE TABLE customer_payment_methods (
    customer_payment_id  UUID PRIMARY KEY,
    customer_id          UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    provider             VARCHAR(50) NOT NULL,
    brand                VARCHAR(25),
    payment_ref_token    TEXT,
    exp_year             SMALLINT NOT NULL,
    exp_month            SMALLINT NOT NULL,
    status               token_status NOT NULL DEFAULT 'PENDING',
    is_default           BOOLEAN NOT NULL DEFAULT FALSE,
    version              INT NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_exp_month_range CHECK (exp_month BETWEEN 1 AND 12)
);

-- ===========================================
-- Indexes
-- ==============================
-- Force one default address per customer
CREATE UNIQUE INDEX uq_default_addr_per_customer
ON customer_addresses(customer_id)
WHERE is_default = TRUE;

-- Force one default payment per customer
CREATE UNIQUE INDEX uq_default_payment_per_customer
ON customer_payment_methods(customer_id)
WHERE is_default = TRUE;